# https://answers.microsoft.com/en-us/protect/forum/protect_defender-protect_start-windows_10/how-do-i-stop-sending-antivirus-samples-to/a2e7b280-a8ba-43f5-b391-0a12c109f990
- name: Install windows defender
  win_feature:
    name: Windows-Defender
  register: win_defender_install

- name: Reboot if needed
  win_reboot:
    reboot_timeout: 600
    post_reboot_delay: 30
  when: win_defender_install.reboot_required

- name: Configure Defender cloud-delivered protection
  win_shell: |
    Set-MpPreference -MAPSReporting 2
    Set-MpPreference -SubmitSamplesConsent 1
    Set-MpPreference -DisableRealtimeMonitoring $false
    Set-MpPreference -DisableScanningMappedNetworkDrivesForFullScan $false
  when: windows_defender_status == "on"

- name: Disable Defender sample submission when explicitly requested
  win_shell: |
    Set-MpPreference -MAPSReporting 0
    Set-MpPreference -SubmitSamplesConsent 2
  when: windows_defender_status == "off"

- name: Disable network drive scanning
  win_shell: Set-MpPreference -DisableScanningMappedNetworkDrivesForFullScan $true
  when: windows_defender_status == "off"

- name: Disable realtime monitoring
  win_shell: Set-MpPreference -DisableRealtimeMonitoring $true
  when: windows_defender_status == "off"

#- name: Uninstall windows defender
#  win_shell: Uninstall-WindowsFeature -Name Windows-Defender
