---
- name: Ensure required services stay enabled
  ansible.windows.win_service:
    name: "{{ item.name }}"
    start_mode: "{{ item.start_mode }}"
    state: started
  loop: "{{ stig_required_services }}"

- name: Disable unsupported services
  ansible.windows.win_service:
    name: "{{ item }}"
    start_mode: disabled
    state: stopped
  loop: "{{ stig_disabled_services }}"
  failed_when: false
